"""add service_access table

Revision ID: 03379d025811
Revises: d3b9ac5a1af1
Create Date: 2026-05-07 17:02:09.424935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03379d025811'
down_revision: Union[str, Sequence[str], None] = 'd3b9ac5a1af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service_id', name='uq_user_service')
    )
    op.create_index(op.f('ix_service_access_service_id'), 'service_access', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_access_user_id'), 'service_access', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_access_user_id'), table_name='service_access')
    op.drop_index(op.f('ix_service_access_service_id'), table_name='service_access')
    op.drop_table('service_access')
    # ### end Alembic commands ###
